### ISSUE TITLE
Isn't the opposite? (error!=0)

### ISSUE THREAD

**Issue by fsantanna** [mnaveenkumar2009/Interrupt-Based-Drivers-for-ceu-arduino#2]
https://github.com/mnaveenkumar2009/Interrupt-Based-Drivers-for-ceu-arduino/blob/c1b15d9c321b6a5722ae7dd94bfb1d3b1a88354c/I2C/sample%202%20bit%20example/psuedocode_master.ceu#L45

**Comment by mnaveenkumar2009** [comment]
yes , will fix it
